name: Sync PDFs from MD
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:      # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required to upload files
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests PyGithub
      - name: Run Downloader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python download_pdfs.py
